# Generated by Django 4.2.2 on 2023-08-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesorderheader',
            options={},
        ),
    ]
